import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';

import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { TemplateComponent } from '@src/app/responsive/template.component';
import { EmployeeComponent } from '@src/app/employee/employee.component';
import { MainNavComponent } from '@src/app/main-nav/main-nav.component';
import { BooksComponent } from '@src/app/books/books.component';
import { DashboardComponent } from '@src/app/dashboard/dashboard.component';
import { FlexComponent } from '@src/app/flex/flex.component';
import { TodoComponent } from '@src/app/todo/todo.component';
import { NavbarComponent } from '@src/app/navbar/navbar.component';


// Uncomment and add to NgModule imports if you need to use two-way binding
// import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
// import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    TemplateComponent,
    EmployeeComponent,
    MainNavComponent,
    BooksComponent,
    DashboardComponent,
    FlexComponent,
    TodoComponent,
    NavbarComponent,
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
